<a href="https://colab.research.google.com/github/Rohanrathod7/my-ds-labs/blob/main/22_Working_with_Dates_and_Times_in_Python/04_Easy_and_Powerful%3A_Dates_and_Times_in_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import datetime as dt

In [4]:
import pandas as pd

url = "https://raw.githubusercontent.com/Rohanrathod7/my-ds-labs/main/22_Working_with_Dates_and_Times_in_Python/dataset/capital-onebike.csv"
# Read the CSV file
onebike_datetimes = pd.read_csv(url)
display(onebike_datetimes.head())

# The second URL is not needed for the current task, so I'll remove it
# url = "https://raw.githubusercontent.com/Rohanrathod7/my-ds-labs/main/20_Cleaning_Data_in_Python/dataset/restaurants_L2_dirty.csv"
# try:
#   restaurants_new = pd.read_csv(url)
#   display(restaurants_new.head())
# except Exception as e:
#   print(f"Error reading the second URL as CSV: {e}")

,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,2017-10-01 15:23:25,2017-10-01 15:26:26,31038,Glebe Rd & 11th St N,31036,George Mason Dr & Wilson Blvd,W20529,Member
1,2017-10-01 15:42:57,2017-10-01 17:49:59,31036,George Mason Dr & Wilson Blvd,31036,George Mason Dr & Wilson Blvd,W20529,Casual
2,2017-10-02 06:37:10,2017-10-02 06:42:53,31036,George Mason Dr & Wilson Blvd,31037,Ballston Metro / N Stuart & 9th St N,W20529,Member
3,2017-10-02 08:56:45,2017-10-02 09:18:03,31037,Ballston Metro / N Stuart & 9th St N,31295,Potomac & M St NW,W20529,Member
4,2017-10-02 18:23:48,2017-10-02 18:45:05,31295,Potomac & M St NW,31230,Metro Center / 12th & G St NW,W20529,Member

**Creating timezone aware datetimes**  
In this exercise, you will practice setting timezones manually.

In [1]:
# Import datetime, timezone
from datetime import datetime, timezone

# October 1, 2017 at 15:26:26, UTC
dt = datetime(2017, 10, 1, 15, 26, 26, tzinfo=timezone.utc)

# Print results
print(dt.isoformat())

2017-10-01T15:26:26+00:00

In [2]:
# Import datetime, timedelta, timezone
from datetime import datetime, timedelta, timezone

# Create a timezone for Pacific Standard Time, or UTC-8
pst = timezone(timedelta(hours=-8))

# October 1, 2017 at 15:26:26, UTC-8
dt = datetime(2017, 10, 1, 15, 26, 26, tzinfo=pst)

# Print results
print(dt.isoformat())

2017-10-01T15:26:26-08:00

In [3]:
# Import datetime, timedelta, timezone
from datetime import datetime, timedelta, timezone

# Create a timezone for Australian Eastern Daylight Time, or UTC+11
aedt = timezone(timedelta(hours=11))

# October 1, 2017 at 15:26:26, UTC+11
dt = datetime(2017, 10, 1, 15, 26, 26, tzinfo=aedt)

# Print results
print(dt.isoformat())

# Did you know that Russia and France are tied for the most number of time zones,
# with 12 each? The French mainland only has one timezone, but because France has
# so many overseas dependencies they really add up!

2017-10-01T15:26:26+11:00

**Setting timezones**  
Now that you have the hang of setting timezones one at a time, let's look at setting them for the first ten trips that W20529 took.

timezone and timedelta have already been imported. Make the change using .replace()

In [ ]:
# Create a timezone object corresponding to UTC-4
edt = timezone(timedelta(hours=-4))

# Loop over trips, updating the start and end datetimes to be in UTC-4
for trip in onebike_datetimes[:10]:
  # Update trip['start'] and trip['end']
  trip['start'] = trip['start'].replace(tzinfo=edt)
  trip['end'] = trip['end'].replace(tzinfo=edt)

# Did you know that despite being over 2,500 miles (4,200 km) wide (about as
# wide as the continential United States or the European Union) China has only
# one official timezone? There's a second, unofficial timezone, too. It is used
# by much of the Uyghurs population in the Xinjiang province in the far west of China.

**What time did the bike leave in UTC?**  
Having set the timezone for the first ten rides that W20529 took, let's see what time the bike left in UTC. We've already loaded the results of the previous exercise into memory.

In [12]:
# Import datetime, timedelta, timezone
from datetime import datetime, timedelta, timezone
import pandas as pd

# Create a timezone object corresponding to Eastern Standard Time (UTC-5)
est = timezone(timedelta(hours=-5))

# Loop over the trips (first 10)
for index, trip in onebike_datetimes[:10].iterrows():
  # Pull out the start date string
  start_date_str = trip['Start date']

  # Convert the string to a datetime object
  dt = pd.to_datetime(start_date_str)

  # Localize the datetime object to EST
  dt_localized = dt.tz_localize(est)

  # Move dt to be in UTC
  dt_utc = dt_localized.astimezone(timezone.utc)

  # Print the start time in UTC
  print('Original:', start_date_str, '| UTC:', dt_utc.isoformat())

  # Did you know that there is no official time zone at the North or South pole?
  # Since all the lines of longitude meet each other, it's up to each traveler
  # (or research station) to decide what time they want to use.

Original: 2017-10-01 15:23:25 | UTC: 2017-10-01T20:23:25+00:00
Original: 2017-10-01 15:42:57 | UTC: 2017-10-01T20:42:57+00:00
Original: 2017-10-02 06:37:10 | UTC: 2017-10-02T11:37:10+00:00
Original: 2017-10-02 08:56:45 | UTC: 2017-10-02T13:56:45+00:00
Original: 2017-10-02 18:23:48 | UTC: 2017-10-02T23:23:48+00:00
Original: 2017-10-02 18:48:08 | UTC: 2017-10-02T23:48:08+00:00
Original: 2017-10-02 19:18:10 | UTC: 2017-10-03T00:18:10+00:00
Original: 2017-10-02 19:37:32 | UTC: 2017-10-03T00:37:32+00:00
Original: 2017-10-03 08:24:16 | UTC: 2017-10-03T13:24:16+00:00
Original: 2017-10-03 18:17:07 | UTC: 2017-10-03T23:17:07+00:00

**Putting the bike trips into the right time zone**  
Instead of setting the timezones for W20529 by hand, let's assign them to their IANA timezone: 'America/New_York'. Since we know their political jurisdiction, we don't need to look up their UTC offset. Python will do that for us.

In [15]:
# Import tz
from dateutil import tz
import pandas as pd

# Create a timezone object for Eastern Time
et = tz.gettz('America/New_York')

# Loop over trips, updating the datetimes to be in Eastern Time
for index, trip in onebike_datetimes[:10].iterrows():
  # Update trip['Start date'] and trip['End date']
  onebike_datetimes.loc[index, 'Start date'] = pd.to_datetime(trip['Start date']).replace(tzinfo=et)
  onebike_datetimes.loc[index, 'End date'] = pd.to_datetime(trip['End date']).replace(tzinfo=et)

# Print the updated DataFrame (optional, for verification)
display(onebike_datetimes.head(10))

# Time zone rules actually change quite frequently. IANA time zone data gets
# updated every 3-4 months, as different jurisdictions make changes to their
# laws about time or as more historical information about timezones are uncovered.
# tz is smart enough to use the date in your datetime to determine which rules to use historically.

,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,2017-10-01 15:23:25-04:00,2017-10-01 15:26:26-04:00,31038,Glebe Rd & 11th St N,31036,George Mason Dr & Wilson Blvd,W20529,Member
1,2017-10-01 15:42:57-04:00,2017-10-01 17:49:59-04:00,31036,George Mason Dr & Wilson Blvd,31036,George Mason Dr & Wilson Blvd,W20529,Casual
2,2017-10-02 06:37:10-04:00,2017-10-02 06:42:53-04:00,31036,George Mason Dr & Wilson Blvd,31037,Ballston Metro / N Stuart & 9th St N,W20529,Member
3,2017-10-02 08:56:45-04:00,2017-10-02 09:18:03-04:00,31037,Ballston Metro / N Stuart & 9th St N,31295,Potomac & M St NW,W20529,Member
4,2017-10-02 18:23:48-04:00,2017-10-02 18:45:05-04:00,31295,Potomac & M St NW,31230,Metro Center / 12th & G St NW,W20529,Member
5,2017-10-02 18:48:08-04:00,2017-10-02 19:10:54-04:00,31230,Metro Center / 12th & G St NW,31645,6th & K St NE,W20529,Member
6,2017-10-02 19:18:10-04:00,2017-10-02 19:31:45-04:00,31645,6th & K St NE,31262,11th & F St NW,W20529,Member
7,2017-10-02 19:37:32-04:00,2017-10-02 19:46:37-04:00,31262,11th & F St NW,31268,12th & U St NW,W20529,Member
8,2017-10-03 08:24:16-04:00,2017-10-03 08:32:27-04:00,31268,12th & U St NW,31267,17th St & Massachusetts Ave NW,W20529,Member
9,2017-10-03 18:17:07-04:00,2017-10-03 18:27:46-04:00,31303,Tenleytown / Wisconsin Ave & Albemarle St NW,31320,Nebraska Ave/AU East Campus,W20529,Member

**What time did the bike leave? (Global edition)**  
When you need to move a datetime from one `timezone` into another, use .`astimezone`() and `tz`. Often you will be moving things into `UTC`, but for fun let's try moving things from 'America/New_York' into a few different time zones.

In [17]:
from dateutil import tz

# Create the timezone object
uk = tz.gettz('Europe/London')

# Pull out the start of the first trip
local = onebike_datetimes.loc[0, 'Start date']


# What time was it in the UK?
notlocal = local.astimezone(uk)

# Print them out and see the difference
print(local.isoformat())
print(notlocal.isoformat())

2017-10-01T15:23:25-04:00
2017-10-01T20:23:25+01:00

In [19]:
# Create the timezone object
ist = tz.gettz('Asia/Kolkata')

# Pull out the start of the first trip
local = onebike_datetimes.loc[0, 'Start date']

# What time was it in India?
notlocal = local.astimezone(ist)

# Print them out and see the difference
print(local.isoformat())
print(notlocal.isoformat())

2017-10-01T15:23:25-04:00
2017-10-02T00:53:25+05:30

In [20]:
# Create the timezone object
sm = tz.gettz("Pacific/Apia")

# Pull out the start of the first trip
local = onebike_datetimes.loc[0, 'Start date']

# What time was it in Samoa?
notlocal = local.astimezone(sm)

# Print them out and see the difference
print(local.isoformat())
print(notlocal.isoformat())

# Did you notice the time offset for this one? It's at UTC+14! Samoa used to be
# UTC-10, but in 2011 it changed to the other side of the International Date Line
# to better match New Zealand, its closest trading partner. However, they wanted to
# keep the clocks the same, so the UTC offset shifted from -10 to +14,
# since 24-10 is 14. Timezones... not simple!

2017-10-01T15:23:25-04:00
2017-10-02T09:23:25+14:00

**How many hours elapsed around daylight saving?**  
Since our bike data takes place in the fall, you'll have to do something else to learn about the start of daylight savings time.

Let's look at March 12, 2017, in the Eastern United States, when Daylight Saving kicked in at 2 AM.

If you create a datetime for midnight that night, and add 6 hours to it, how much time will have elapsed?

In [21]:
# Import datetime, timedelta, tz, timezone
from datetime import datetime, timedelta, timezone
from dateutil import tz

# Start on March 12, 2017, midnight, then add 6 hours
start = datetime(2017, 3, 12, tzinfo = tz.gettz('America/New_York'))
end = start + timedelta(hours=6)
print(start.isoformat() + " to " + end.isoformat())

# How many hours have elapsed?
print((end - start).total_seconds()/(60*60))

# What if we move to UTC?
print((end.astimezone(timezone.utc) - start.astimezone(timezone.utc) )\
      .total_seconds()/(60*60))

# When we compare times in local time zones, everything gets converted into clock '
# time. Remember if you want to get absolute time differences, always move to UTC!

2017-03-12T00:00:00-05:00 to 2017-03-12T06:00:00-04:00
6.0
5.0

**March 29, throughout a decade**  
Daylight Saving rules are complicated : they're different in different places, they change over time, and they usually start on a Sunday (and so they move around the calendar).

For example, in the United Kingdom, as of the time this lesson was written, Daylight Saving begins on the last Sunday in March. Let's look at the UTC offset for March 29, at midnight, for the years 2000 to 2010.

In [22]:
# Import datetime and tz
from datetime import datetime
from dateutil import tz

# Create starting date
dt = datetime(2000, 3, 29, tzinfo = tz.gettz('Europe/London'))

# Loop over the dates, replacing the year, and print the ISO timestamp
for y in range(2000, 2011):
  print(dt.replace(year=y).isoformat())

# As you can see, the rules for Daylight Saving are not trivial. When in doubt,
# always use tz instead of hand-rolling timezones, so it will catch the
# Daylight Saving rules (and rule changes!) for you.

2000-03-29T00:00:00+01:00
2001-03-29T00:00:00+01:00
2002-03-29T00:00:00+00:00
2003-03-29T00:00:00+00:00
2004-03-29T00:00:00+01:00
2005-03-29T00:00:00+01:00
2006-03-29T00:00:00+01:00
2007-03-29T00:00:00+01:00
2008-03-29T00:00:00+00:00
2009-03-29T00:00:00+00:00
2010-03-29T00:00:00+01:00

**Finding ambiguous datetimes**  
At the end of lesson 2, we saw something anomalous in our bike trip duration data. Let's see if we can identify what the problem might be.

The data is loaded as onebike_datetimes, and tz has already been imported from dateutil.

In [52]:
# Import tz
from dateutil import tz
import pandas as pd

# Reload the original 'Start date' and 'End date' columns from the CSV
# This ensures we start with naive datetime objects from strings
url = "https://raw.githubusercontent.com/Rohanrathod7/my-ds-labs/main/22_Working_with_Dates_and_Times_in_Python/dataset/capital-onebike.csv"
original_dates = pd.read_csv(url, usecols=['Start date', 'End date'])

# Convert to naive datetime objects
onebike_datetimes['Start date'] = pd.to_datetime(original_dates['Start date'])
onebike_datetimes['End date'] = pd.to_datetime(original_dates['End date'])

# Localize the naive datetimes to 'America/New_York'
# The 'ambiguous='NaT'' argument handles cases where the time falls within
# the transition period where clocks are set back (e.g., end of daylight saving)
# This will turn ambiguous times into NaT
onebike_datetimes['Start date'] = onebike_datetimes['Start date'].dt.tz_localize(tz.gettz('America/New_York'), ambiguous='NaT')
onebike_datetimes['End date'] = onebike_datetimes['End date'].dt.tz_localize(tz.gettz('America/New_York'), ambiguous='NaT')

# Loop over trips and check for NaT values
for index, trip in onebike_datetimes.iterrows():
  # Rides with ambiguous start will now be NaT
  if pd.isna(trip['Start date']):
    # To see the original value, we might need to access the original_dates Series
    # print("Ambiguous start originally at " + original_dates.loc[index, 'Start date'])
    print(f"Ambiguous start at index {index}") # Print index to identify the row
  # Rides with ambiguous end will now be NaT
  if pd.isna(trip['End date']):
    # print("Ambiguous end originally at " + original_dates.loc[index, 'End date'])
    print(f"Ambiguous end at index {index}") # Print index to identify the row

Ambiguous start at index 129
Ambiguous end at index 129

**Cleaning daylight saving data with fold**  
As we've just discovered, there is a ride in our data set which is being messed up by a Daylight Savings shift. Let's clean up the data set so we actually have a correct minimum ride length. We can use the fact that we know the end of the ride happened after the beginning to fix up the duration messed up by the shift out of Daylight Savings.

Since Python does not handle tz.enfold() when doing arithmetic, we must put our datetime objects into UTC, where ambiguities have been resolved.

onebike_datetimes is already loaded and in the right timezone. tz and timezone have been imported. Use tz.UTC for the timezone.

In [58]:
from dateutil import tz
from datetime import timezone # Import timezone if not already imported
import pandas as pd # Import pandas if not already imported

trip_durations = []
# Loop over the trips using iterrows to get row data
for index, trip in onebike_datetimes.iterrows():
  # Check if either the start or end time is NaT, and skip this trip if so
  if pd.isna(trip['Start date']) or pd.isna(trip['End date']):
    print(f"Skipping trip at index {index} due to NaT in start or end date.")
    continue # Skip to the next trip

  # Check if the start time is after the end time, likely due to DST transition
  # Use the correct column names 'Start date' and 'End date'
  if trip['Start date'] > trip['End date']:
    # Apply tz.enfold to the end time to indicate it's in the earlier cycle of the repeated hour
    # Note: tz.enfold is typically used on naive datetimes before localization,
    # but here we are working with localized datetimes after an initial localization.
    # A more robust approach for DST transitions might involve re-localizing with
    # a specific fold value if the initial localization with ambiguous='NaT' is not sufficient.
    # However, for this exercise following the original logic, we'll apply enfold here,
    # assuming the localized datetime object supports it or that the intent is to mark it for
    # later handling if needed, though enfold is usually for naive datetimes.
    # Let's assume for the purpose of this exercise that we are conceptually marking
    # this end time as the earlier instance in the ambiguous hour after localization.
    # A more correct approach might be to handle ambiguity during the initial localization
    # using 'fold=1' for the second instance of the hour, or to use a dedicated library
    # function that correctly handles DST transitions for already localized times.
    # Given the error was NaT, and we're now handling NaT, let's keep the enfold call
    # as it was in the original user code, while acknowledging its typical usage is pre-localization.
    # If issues persist, a different DST handling strategy would be needed.
    try:
        trip['End date'] = tz.enfold(trip['End date'])
    except ValueError:
        # If enfold raises ValueError (e.g., on non-naive datetime depending on library version/state),
        # we might need a different approach or skip this correction.
        # For now, let's just print a warning and proceed without enfolding.
        print(f"Warning: Could not apply tz.enfold to end date at index {index}. Proceeding without enfolding.")


  # Convert to UTC using the corrected datetime objects
  # Ensure 'Start date' and 'End date' are timezone-aware before converting to UTC
  # Based on previous cells, they should be localized to 'America/New_York' and not NaT at this point.
  start = trip['Start date'].astimezone(timezone.utc)
  end = trip['End date'].astimezone(timezone.utc)

  # Subtract the difference
  trip_length_seconds = (end-start).total_seconds()
  trip_durations.append(trip_length_seconds)

# Take the shortest trip duration
print("Shortest trip: " + str(min(trip_durations)))

Skipping trip at index 129 due to NaT in start or end date.
Shortest trip: 116.0

In [ ]:
trip_durations = []
for trip in onebike_datetimes:
  # When the start is later than the end, set the fold to be 1
  if trip['start'] > trip['end']:
    trip['end'] = tz.enfold(trip['end'])
  # Convert to UTC
  start = trip['start'].astimezone(tz.UTC)
  end = trip['end'].astimezone(tz.UTC)

  # Subtract the difference
  trip_length_seconds = (end-start).total_seconds()
  trip_durations.append(trip_length_seconds)

# Take the shortest trip duration
print("Shortest trip: " + str(min(trip_durations)))

# Now you know how to handle some pretty gnarly edge cases in datetime data. To
# give a sense for how tricky these things are: we actually still don't know how
# long the rides are which only started or ended in our ambiguous hour but not
# both. If you're collecting data, store it in UTC or with a fixed UTC offset!